---
title: "Infrastructure"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}

library(sf)
library(tidyverse)
library(tigris)
library(leaflet)
library(arcpullr)

```

```{r watershed}
waterbasins <- c("Upper Catawba",
                 "Lower Catawba",
                 "South Fork Catawba",
                 "Wateree")

watershed <- st_read("data/WBD_03_HU2_Shape/Shape/WBDHU8.shp") %>%
  dplyr::filter(name %in% waterbasins ) %>%
  st_transform(crs="EPSG:4326") %>%
  st_union(.)

```

```{r admin boundaries}
counties <- rbind(
  counties(state="North Carolina"), 
  counties(state="South Carolina")
  ) %>%
  st_transform(crs="EPSG:4326") 


counties_watershed <- counties %>%
  st_intersection(., watershed)

counties_list <- counties_watershed$GEOID

counties_watershed_full <- counties %>%
  dplyr::filter(GEOID %in% counties_list)

ggplot()+
  geom_sf(data = counties_watershed_full) + 
  geom_sf(data = watershed, color = "blue", fill = NA)

munis_watershed <- rbind(
  county_subdivisions(state="North Carolina"), 
  county_subdivisions(state="South Carolina")
  ) %>%
  st_transform(crs="EPSG:4326")

counties_catawba <- st_intersection(counties_watershed, watershed)

munis_catawba <- st_intersection(munis_watershed, watershed)

counties_catawba_list <- counties_catawba$NAME
munis_catawba_list <- munis_catawba %>%
  dplyr::select(NAMELSAD, STATEFP) %>%
  st_drop_geometry(.)

ggplot()+
  geom_sf(data = counties)

```

```{r drinking water data}

nc_infra <- get_spatial_layer("https://services.nconemap.gov/secure/rest/services/NC1Map_Water_Sources/MapServer/1")%>%
  st_transform(crs="EPSG:4326")%>%
  st_intersection(., watershed) %>%
  dplyr::filter(pws_type == "Community", source_availability == "Permanent")

nc_infra_intake = nc_infra %>%
  dplyr::filter(source_type == "Surface Water") 

nc_infra_intake2 = nc_infra %>%
  dplyr::filter(source_type == "Surface Water") %>%
  dplyr::select(objectid, geoms)

nc_infra_wells = nc_infra %>%
  dplyr::filter(source_type == "Groundwater")

nc_infra_wells2 = nc_infra %>%
  dplyr::filter(source_type == "Groundwater") %>%
  dplyr::select(objectid, geoms)

sc_infra_intake <- get_spatial_layer("https://gis.dhec.sc.gov/arcgis/rest/services/water/publicwatersupply/MapServer/0")%>%
  st_transform(crs="EPSG:4326")%>%
  st_intersection(., watershed)

sc_infra_intake2 <- sc_infra_intake %>%
  dplyr::select(OBJECTID, geoms) %>%
  dplyr::rename(objectid = OBJECTID)

sc_infra_wells <- get_spatial_layer("https://gis.dhec.sc.gov/arcgis/rest/services/water/publicwatersupply/MapServer/1")%>%
  st_transform(crs="EPSG:4326")%>%
  st_intersection(., watershed)

sc_infra_wells2 <- sc_infra_wells %>%
  dplyr::select(OBJECTID, geoms)%>%
  dplyr::rename(objectid = OBJECTID)

infra <- rbind(nc_infra_intake2, nc_infra_wells2, sc_infra_intake2, sc_infra_wells2)



```

```{r treatment plant}

treatment_plant <- st_read("data/NC_SC_epa_frs_FeaturesToJson.geojson") %>%
  dplyr::filter(FIPS_CODE %in% counties_list) %>%
  dplyr::filter(INTEREST_TYPE == "WATER TREATMENT PLANT") %>%
  st_transform(crs="EPSG:4326") %>%
  st_intersection(., watershed)

```

```{r hydro generator}

hydroelectric <- st_read("data/NC_SC_epa_frs_FeaturesToJson.geojson") %>%
  dplyr::filter(FIPS_CODE %in% counties_list) %>%
  dplyr::filter(INTEREST_TYPE == "ELECTRIC POWER GENERATOR (WATER BASED)") %>%
  st_transform(crs="EPSG:4326") %>%
  st_intersection(., watershed)

```

```{r environmental justice index}

eji <- rbind(
  st_read("data/North Carolina/North Carolina.gdb"),
  st_read("data/South Carolina/South Carolina.gdb")
  ) %>%
  st_transform(crs="EPSG:4326") %>%
  st_intersection(., watershed)

```

```{r map}

ggplot() +
  geom_sf(data = watershed) +
  #(data = eji) +
  geom_sf(data = sc_infra_wells, color = "yellow") +
  geom_sf(data = nc_infra_wells, color = "yellow") +
  geom_sf(data = sc_infra_intake, color = "blue") +
  geom_sf(data = nc_infra_intake, color = "blue") + 
  geom_sf(data = treatment_plant, color = "red") +
  geom_sf(data = hydroelectric, color = "green") +
  theme_minimal()

ggplot()+
  geom_sf(data = watershed) +
  geom_sf(data = infra)

```

```{r dbscan}
library(dbscan)
library(factoextra)

infra_proj <- infra %>%
  st_transform("EPSG:32119")

coords <- as.data.frame(st_coordinates(infra_proj$geoms))

clust <- dbscan(x = coords, 10000, 50, borderPoints = FALSE)

clust

ggplot(clust, aes(x = lon, y = lat, color = cluster)) +
  geom_point() +
  labs(title = "DBSCAN Clustering Results")

fviz_cluster(clust, data = coords)

```

```{r kmeans}
library(cluster)

df <- USArrests
df <- na.omit(df)
df <- scale(df)

k2 <- kmeans(df, centers = 2, nstart = 5)

fviz_cluster(k2, data = df)

set.seed(124)

fviz_nbclust(df, kmeans, method = "wss")

```