---
title: "County Subdivisions"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
```

```{r packages}

library(tidycensus)
library(tidyverse)
library(tigris)
library(sf)
library(arcpullr)

options(scipen = 999)
census_api_key("e13d5be5cb48d927009e0dca0af99d21918d514f", overwrite = TRUE)
```

```{r map_theme, include = FALSE}

theme_catawba <- function(){
  font = "sans"
  theme_minimal() %+replace%
    
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      
      axis.ticks = element_blank(),
      axis.ticks.x.bottom = element_line(color = "grey90", size = .5),
      
      plot.title = element_text(
        family = font,
        size = 14,
        face = 'bold',
        hjust = 0,
        vjust = 0),

      plot.subtitle = element_text(
        family = font,
        size = 12,
        hjust = 0,
        margin = margin(2, b = 10),
        face = "italic"),
      
      plot.caption = element_text(
        family = font,
        size = 10,
        hjust = 1),
      
      axis.title = element_text(
        family = font,
        size = 10,
        margin = margin(5, b = 10)),
      
      axis.text = element_blank()
      )
}

```

```{r waterbasins}
waterbasins <- c("Upper Catawba",
                 "Lower Catawba",
                 "South Fork Catawba",
                 "Wateree")

waterbasin <- st_read("data/WBD_03_HU2_Shape/Shape/WBDHU8.shp") %>%
  dplyr::filter(name %in% waterbasins ) %>%
  st_transform(crs="EPSG:4326")

watershed <- st_read("data/WBD_03_HU2_Shape/Shape/WBDHU8.shp") %>%
  dplyr::filter(name %in% waterbasins ) %>%
  st_transform(crs="EPSG:4326") %>%
  st_union(.)

bbox <- st_bbox(watershed)
bbox_sf <- st_as_sfc(st_bbox(watershed))

```

```{r tracts}

nc_tracts <- get_acs(
  geography = "tract",
  variables = "B01003_001",
  state = "North Carolina", 
  geometry = TRUE,
  output = "wide",
  year = 2019
)

sc_tracts <- get_acs(
  geography = "tract",
  variables = "B01003_001",
  state = "South Carolina", 
  geometry = TRUE,
  output = "wide",
  year = 2019
)

nc_counties <- get_acs(
  geography = "county",
  variables = "B01003_001",
  state = "North Carolina", 
  geometry = TRUE,
  output = "wide",
  year = 2019
)

sc_counties <- get_acs(
  geography = "county",
  variables = "B01003_001",
  state = "South Carolina", 
  geometry = TRUE,
  output = "wide",
  year = 2019
)

tn_counties <- get_acs(
  geography = "county",
  variables = "B01003_001",
  state = "Tennessee", 
  geometry = TRUE,
  output = "wide",
  year = 2019
)

ga_counties <- get_acs(
  geography = "county",
  variables = "B01003_001",
  state = "Georgia", 
  geometry = TRUE,
  output = "wide",
  year = 2019
)

state_abbr <- c("NC", "SC", "TN", "GA")

states <- states() %>%
  filter(STUSPS %in% state_abbr)

nc_places <- get_acs(
  geography = "place",
  variables = "B01003_001",
  state = "North Carolina", 
  geometry = TRUE,
  output = "wide",
  year = 2019
)%>%
  rename(pop = B01003_001E)%>%
  st_transform(crs="EPSG:4326")

sc_places <- get_acs(
  geography = "place",
  variables = "B01003_001",
  state = "South Carolina", 
  geometry = TRUE,
  output = "wide",
  year = 2019
)%>%
  rename(pop = B01003_001E)%>%
  st_transform(crs="EPSG:4326")

places_points <- rbind(st_centroid(nc_places), st_centroid(sc_places))%>%
  st_intersection(., bbox_sf)

catawba_points <- places_points %>%
  st_intersection(.,watershed)

```




```{r watershed tracts}



counties <- rbind(nc_counties, sc_counties, tn_counties, ga_counties) %>%
  st_transform(crs="EPSG:4326") %>%
  rename(pop = B01003_001E) %>%
  dplyr::select(-B01003_001M)%>%
  st_intersection(., bbox_sf)

catawba_tracts <- rbind(nc_tracts, sc_tracts) %>%
  st_transform(crs="EPSG:4326") %>%
  rename(pop = B01003_001E) %>%
  dplyr::select(-B01003_001M) %>%
  st_intersection(., watershed)


ggplot()+
  geom_sf(data=counties, color = alpha("white", .5), lwd = .1, aes(fill = pop)) +
  geom_sf(data=states, color = "white", lwd = 2, fill = NA)+
  geom_sf(data=catawba_points, color = alpha("gold", .75), aes(size = pop)) +
  geom_sf(data=watershed, color = alpha("orangered", .75), lwd = 2, fill = NA) +
  scale_fill_viridis_c(option="mako", direction = -1)+
  coord_sf(xlim = c(bbox$xmin, bbox$xmax), ylim = c(bbox$ymin, bbox$ymax))+
  theme_catawba()

```

```{r eji}

nc_eji <- st_read("data/North Carolina/North Carolina.gdb") %>%
  st_intersection(.,watershed)
sc_eji <- st_read("data/South Carolina/South Carolina.gdb") %>%
  st_intersection(.,watershed)

eji <- rbind(nc_eji, sc_eji)

ggplot()+
  geom_sf(data=eji, aes(fill = SPL_EJI), color=NA) +
  scale_fill_viridis_c()+
  theme_catawba()

ggplot()+
  geom_sf(data=eji, aes(fill = RPL_EBM), color=NA) +
  scale_fill_viridis_c()+
  theme_catawba()

ggplot()+
  geom_sf(data=eji, aes(fill = EPL_IMPWTR), color=NA) +
  scale_fill_viridis_c()+
  theme_catawba()



```

```{r drinking water data}

# nc_infra <- get_spatial_layer("https://services.nconemap.gov/secure/rest/services/NC1Map_Water_Sources/MapServer/1")%>%
#   st_transform(crs="EPSG:4326")%>%
#   st_intersection(., watershed) %>%
#   dplyr::filter(pws_type == "Community", source_availability == "Permanent")
# 
# nc_infra_intake = nc_infra %>%
#   dplyr::filter(source_type == "Surface Water") 
# 
# nc_infra_intake2 = nc_infra %>%
#   dplyr::filter(source_type == "Surface Water") %>%
#   dplyr::select(objectid, geoms)
# 
# nc_infra_wells = nc_infra %>%
#   dplyr::filter(source_type == "Groundwater")
# 
# nc_infra_wells2 = nc_infra %>%
#   dplyr::filter(source_type == "Groundwater") %>%
#   dplyr::select(objectid, geoms)

sc_infra_intake <- get_spatial_layer("https://gis.dhec.sc.gov/arcgis/rest/services/water/publicwatersupply/MapServer/0")%>%
  st_transform(crs="EPSG:4326")%>%
  st_intersection(., watershed)

sc_infra_intake2 <- sc_infra_intake %>%
  dplyr::select(OBJECTID, geoms) %>%
  dplyr::rename(objectid = OBJECTID)

sc_infra_wells <- get_spatial_layer("https://gis.dhec.sc.gov/arcgis/rest/services/water/publicwatersupply/MapServer/1")%>%
  st_transform(crs="EPSG:4326")%>%
  st_intersection(., watershed)

sc_infra_wells2 <- sc_infra_wells %>%
  dplyr::select(OBJECTID, geoms)%>%
  dplyr::rename(objectid = OBJECTID)

#infra <- rbind(nc_infra_intake2, nc_infra_wells2, sc_infra_intake2, sc_infra_wells2)


```

```{r sc data}

sc_dams <- st_read("data/sc_dams.geojson") %>%
  st_transform(crs="EPSG:4326")

sc_ms4 <- st_read("data/sc_MS4.geojson") %>%
  mutate(geometry = st_make_valid(st_zm(geometry)))

sc_npdes <- st_read("data/sc_NPDES_Permits.geojson")

intersection <- st_intersection(catawba_tracts_sc, sc_ms4)


# Count the number of polygons from MS4 touching each census tract
count_per_tract <- intersection %>%
  group_by(GEOID) %>%
  summarise(count = n()) %>%
  st_drop_geometry()

# Join the counts back to census tracts
catawba_tracts_sc1 <- left_join(catawba_tracts_sc, count_per_tract, by = c("GEOID" = "GEOID")) %>%
  mutate(count = ifelse(is.na(count), 0, count))

within <- st_join(sc_infra_intake, catawba_tracts_sc1, join = st_within)

# Count the number of points from intake dataset within each census tract
count_per_tract <- within %>%
  group_by(GEOID) %>%
  summarise(intakes = n())%>%
  st_drop_geometry()

# Join the counts back to census tracts
catawba_tracts_sc1 <- left_join(catawba_tracts_sc1, count_per_tract, by = "GEOID") %>%
  mutate(intakes = ifelse(is.na(intakes), 0, intakes))

within2 <- st_join(sc_infra_wells, catawba_tracts_sc1, join = st_within)

count_per_tract1 <- within2 %>%
  group_by(GEOID) %>%
  summarise(wells = n())%>%
  st_drop_geometry()

catawba_tracts_sc1 <- left_join(catawba_tracts_sc1, count_per_tract1, by = "GEOID") %>%
  mutate(wells = ifelse(is.na(wells), 0, wells))

within3 <- st_join(sc_npdes, catawba_tracts_sc1, join = st_within)

count_per_tract1 <- within3 %>%
  group_by(GEOID) %>%
  summarise(permits = n())%>%
  st_drop_geometry()

catawba_tracts_sc1 <- left_join(catawba_tracts_sc1, count_per_tract1, by = "GEOID") %>%
  mutate(permits = ifelse(is.na(permits), 0, permits))

sc_eji1 <- sc_eji %>%
  dplyr::select(GEOID, SPL_EJI, RPL_EBM, EPL_IMPWTR) %>%
  st_drop_geometry()

catawba_tracts_sc1 <- left_join(catawba_tracts_sc1, sc_eji1, by = "GEOID") %>% na.omit()

catawba_tracts_geo <- catawba_tracts_sc1 %>%
  dplyr::select(GEOID, geometry)



sc_srf <- read_csv("data/sc_srf_catawba.csv")
sc_srf_points <- st_as_sf(sc_srf, coords = c("longitude", "latitude"), crs = 4326)
sc_srf_catawba <- st_intersection(sc_srf_points, watershed)

within4 <- st_join(sc_srf_catawba, catawba_tracts_sc1, join = st_within)

count_per_tract1 <- within4 %>%
  group_by(GEOID) %>%
  summarise(invest = sum(total_proj_cost_est))%>%
  st_drop_geometry()

catawba_tracts_sc1 <- left_join(catawba_tracts_sc1, count_per_tract1, by = "GEOID") %>%
  mutate(invest = ifelse(is.na(invest), 0, invest))


within5 <- st_join(sc_dams, catawba_tracts_sc1, join = st_within)

count_per_tract1 <- within5 %>%
  group_by(GEOID) %>%
  summarise(dams = n())%>%
  st_drop_geometry()

catawba_tracts_sc1 <- left_join(catawba_tracts_sc1, count_per_tract1, by = "GEOID") %>%
  mutate(dams = ifelse(is.na(dams), 0, dams))

```

```{r dbscan}
library(dbscan)


df_g <- 


```

```{r kmeans}

library(cluster)
library(factoextra)
library(kableExtra)
set.seed(124)


df <- catawba_tracts_sc1

row.names(df) <- df[[1]]


df <- df %>%
  dplyr::select(-GEOID, -NAME, -RPL_EBM, -EPL_IMPWTR) %>%
  st_drop_geometry()

df_scaled <- scale(df)

clusters <- kmeans(df_scaled, centers = 3, nstart = 5)

cluster_centers <- clusters$centers

cluster_centers_df <- as.data.frame(cluster_centers)

#fviz_cluster(clusters, data = df)

fviz_nbclust(df_scaled, kmeans, method = "wss")

df <- cbind(df, cluster = clusters$cluster)

# Get the row names
row_names <- rownames(df)

# Reset row names
rownames(df) <- NULL

# Add row names as a regular column
df <- cbind(GEOID = row_names, df)
df$cluster <- as.character(df$cluster)


catawba_tracts_sc2 <- left_join(catawba_tracts_geo, df, by = "GEOID")

catawba_tracts_sc2 <- st_as_sf(catawba_tracts_sc2)


ggplot()+
  geom_sf(data=catawba_tracts_sc2, aes(fill = cluster))

cluster_centers_df %>%
  kbl(digits=2) %>%
  kable_minimal()

#library(wskm) kmeans.weight


```
